# Generated by Django 5.0.14 on 2026-09-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('model_name', models.CharField(max_length=120)),
                ('imei_number', models.CharField(max_length=20, unique=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used / Refurbished')], default='NEW', max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available for sale'), ('ON_LOAN', 'Given on loan'), ('SOLD', 'Sold (cash)'), ('RETURNED', 'Returned to supplier')], default='AVAILABLE', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
