# Generated by Django 6.1 on 2026-08-31 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('id_proof_type', models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('VOTER', 'Voter ID'), ('PASSPORT', 'Passport')], default='AADHAR', max_length=20)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_score', models.IntegerField(default=650, help_text='Simple internal score used for loan eligibility')),
                ('is_verified', models.BooleanField(default=False, help_text='KYC verified by staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
