# Generated by Django 5.0.14 on 2026-09-01 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('id_proof_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('VOTER_ID', 'Voter ID'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('OTHER', 'Other')], default='AADHAAR', max_length=20)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/photos/')),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
