# Generated by Django 5.0.14 on 2026-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_proof_type',
            field=models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('VOTER_ID', 'Voter iD'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('OTHER', 'Other')], default='AADHAAR', max_length=20),
        ),
    ]
