# Generated by Django 5.0.14 on 2026-09-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_is_active_alter_customer_id_proof_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_active',
            new_name='not_active',
        ),
    ]
