# Generated by Django 5.0.14 on 2026-09-01 07:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text="Phone's selling price", max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual interest rate in percent, e.g. 12.00 for 12%', max_digits=5)),
                ('tenure_months', models.PositiveIntegerField(help_text='Number of monthly installments')),
                ('monthly_emi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='total_amount - down_payment; the amount actually financed', max_digits=10)),
                ('start_date', models.DateField(help_text='Date the loan begins / phone handed over')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed / Fully Paid'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='customers.customer')),
                ('mobile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='inventory.mobilephone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EMIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partially Paid')], default='PENDING', max_length=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
            ],
            options={
                'ordering': ['loan', 'installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
