# Generated by Django 5.0.14 on 2026-09-06 20:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emipayment',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty added once this installment goes overdue.', max_digits=8),
        ),
    ]
